### Numpy over List
- faster 
    - fixed typr
    - uses contiguous memory
           - SIMD Vector Processing 
           - effective cache utilization
- can do more computtions

### Applications
- mathematics(MATLAB Replacement)
- Plotting(Matplotlib)
- Backend(paandas,connect 4,Digital photography)
- ML applications

In [2]:
import numpy as np

### The Basics

In [84]:
# Reading array
# 1D array
a = np.array([1,2,3])
print(a)

# 2D array
b = np.array([[9.0,8.0,7.0],[6.0,5.0,3.0]])
print(b)

[1 2 3]
[[9. 8. 7.]
 [6. 5. 3.]]


In [32]:
# Get Dimension
a.ndim
b.ndim

2

In [33]:
# Get shape
a.shape
# b.shape

(3,)

In [34]:
# get Type
a.dtype
b.dtype

dtype('float64')

In [35]:
# SPECIFYING DATATYPE 
a = np.array([1,2,3],dtype = 'int16')

In [36]:
a.dtype

dtype('int16')

In [37]:
# GET SIZE
a.itemsize
b.itemsize

8

In [38]:
# GET TOTAL SIZE
a.nbytes


6

### Accessing and Changing specific elements,rows,columns,...

In [14]:
n = np.array([[1,2,3,4,5],
              [8,9,10,11,12]])
print(n)

[[ 1  2  3  4  5]
 [ 8  9 10 11 12]]


In [78]:
# Get a specific elemet [r,c]
n[1, 4]

12

In [79]:
n.ndim

2

In [80]:
# Get specify row
n[0,:]

array([1, 2, 3, 4, 5])

In [81]:
# get specific column
n[:,2]

array([ 3, 10])

In [82]:
# getting a little more fancy[startindex:endindex:stepsize]
n[0,1:-1:2]

array([2, 4])

In [83]:
n[1,4] = 20
print(n)
n[:,2] = [1,2]
print(n)

[[ 1  2  3  4  5]
 [ 8  9 10 11 20]]
[[ 1  2  1  4  5]
 [ 8  9  2 11 20]]


In [86]:
# 3D array
m = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(m)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [92]:
# replace
m[:,1,:] = [[0,9,0],[8,8]]

ValueError: setting an array element with a sequence.

In [93]:
# get specific element(work outside in)

m[0,1,1]

4

# Initializing Diff Types of Arrays
 - np.ones
 - np.zeroes
 - np.full
 - np.full_like


In [5]:
# All 0's matrix
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [11]:
# All 1's matrix
np.ones((2,3))
np.ones((4,2,3),dtype='int32')

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [12]:
# Fill with single value
np.full(shape,value_to_be_filled)
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [16]:
# Any other number(full_like)
np.full_like(n.shape,2)
np.full_like(n,2)

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [23]:
# Random decimal numbers
# np.random.rand((4,2))---error
np.random.random_sample(n.shape)
np.random.rand(4,2)

array([[0.81124291, 0.63088576],
       [0.52837798, 0.30307624],
       [0.42317586, 0.5990789 ],
       [0.43923997, 0.16176848]])

In [26]:
# Random integer values
np.random.randint(7)
np.random.randint(7,size=(3,3))  #its not shape its size
np.random.randint(-2,7,size=(3,3))  #its not shape its size

array([[ 3,  4,  5],
       [ 0,  0,  5],
       [ 2, -1,  4]])

In [27]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
# Repeat an array
arr = np.array([[1,2,3]])
rl = np.repeat(arr,3,axis=0)
print(rl)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [46]:
output = np.ones((5,5))
print(output)


z = np.zeros((3,3))
z[1,1] = 9
print(z)

# output[1:4,1:4]=z
output[1:-1,1:-1]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Be careful when copying arrays!!!
 - make sure you use copy() not to change original array

In [48]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)

[100   2   3]


In [50]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]


### Mathematics

In [62]:
a= np.array([1,2,3])
print(a)

[1 2 3]


In [63]:
a + 2

array([3, 4, 5])

In [64]:
a - 2

array([-1,  0,  1])

In [65]:
a * 2

array([2, 4, 6])

In [66]:
a / 2

array([0.5, 1. , 1.5])

In [68]:
# Applying Trinomentry 
np.cos(a)


array([ 0.54030231, -0.41614684, -0.9899925 ])

## Linear Algebra

In [75]:
a=np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [77]:
# find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [78]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)
# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse

### Statistics

In [81]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
np.min(stats)

1

In [83]:
np.max(stats,axis = 1)

array([3, 6])

In [85]:
np.sum(stats,axis = 0)

array([5, 7, 9])

### Reorganizing Arrays

In [90]:
before = np.array([[1,2,3],[4,5,6]])
print(before)

after = before.reshape((6,1))
print(after)

[[1 2 3]
 [4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [93]:
# Vertically Stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [96]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## Micellaneous

In [97]:
### Load Data from file

In [100]:
filedata = np.genfromtxt('data.txt',delimiter=',',dtype = "int32")
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

In [102]:
filedata = np.genfromtxt('data.txt',delimiter=',')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

### Boolean Masking and Advanced indexing 

In [103]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [104]:
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [108]:
## You can index with a list in Numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [111]:
np.all(filedata > 50,axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [112]:
np.any(filedata > 50,axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [114]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [115]:
~((filedata > 50) & (filedata < 100))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])